# Generated by Django 3.0.6 on 2021-06-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='available',
            field=models.IntegerField(choices=[(0, '利用可能'), (1, '利用不可能')], default=0),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='status',
            field=models.IntegerField(choices=[(0, '予約中'), (1, '予約キャンセル'), (2, '返却'), (3, '事故')], default=0),
        ),
    ]
